CREATE TABLE PESSOAS(
    ID BIGSERIAL PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100),
    NOME_FANTASIA VARCHAR(100),
    CPF VARCHAR(14),
    CNPJ VARCHAR(18),
    TIPO_PESSOA VARCHAR(20),
    TIPO_PARCEIRO VARCHAR(50)
);