CREATE TABLE TELEFONES(
    ID UUID PRIMARY KEY,
    NUMERO VARCHAR(20),
    PESSOA_ID BIGSERIAL NOT NULL,
    TIPO_TELEFONE VARCHAR(20),
    CONSTRAINT fk_telefone_pessoa FOREIGN KEY (PESSOA_ID) REFERENCES PESSOAS(ID)
);