CREATE TABLE PRODUTOS(
    ID BIGSERIAL NOT NULL,
    DESCRICAO VARCHAR(50),
    CUSTO_UNITARIO NUMERIC(15,2),
    VALOR_UNITARIO NUMERIC(15,2),
    CATEGORIA_ID BIGSERIAL,
    FORNECEDOR_ID BIGSERIAL,
    CONSTRAINT fk_categoriaproduto_produto FOREIGN KEY (CATEGORIA_ID) REFERENCES PRODUTOS_CATEGORIAS(ID),
    CONSTRAINT fk_fornecedor_produto FOREIGN KEY (FORNECEDOR_ID) REFERENCES PESSOAS(ID)
);