CREATE TABLE PESSOA_TIPO_PARCEIRO(
    PESSOA_ID BIGINT NOT NULL,
    TIPO_PARCEIRO VARCHAR(30) NOT NULL,
    CONSTRAINT FK_PESSOA_TIPO_PARCEIRO
       FOREIGN KEY (PESSOA_ID)
       REFERENCES PESSOAS(ID)
);