CREATE TABLE USUARIOS(
    ID BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(255),
    ACTIVE BOOLEAN,
    PESSOA_ID BIGSERIAL
);

CREATE INDEX IDX_USUARIOS_ID ON USUARIOS (ID);

CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS (EMAIL);