CREATE TABLE USUARIOS(
    ID BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(255),
    ACTIVE BOOLEAN,
    PESSOA_ID BIGSERIAL,

    CONSTRAINT FK_USUARIOS_PESSOA FOREIGN KEY (PESSOA_ID)
                    REFERENCES PESSOAS(ID)
);

CREATE INDEX IDX_USUARIOS_ID ON USUARIOS (ID);

CREATE INDEX IDX_USUARIOS_EMAIL ON USUARIOS (EMAIL);