
CREATE INDEX IDX_PESSOAS_ID ON PESSOAS(ID);
CREATE INDEX IDX_PESSOAS_CPF ON PESSOAS(CPF);

CREATE INDEX IDX_TELEFONES_ID ON TELEFONES (ID);
CREATE INDEX IDX_TELEFONES_ID_PESSOA ON TELEFONES (ID, PESSOA_ID);

CREATE INDEX IDX_PRODUTOSCATEGORIAS_ID ON PRODUTOS_CATEGORIAS (ID);

CREATE INDEX IDX_PRODUTOS_ID ON PRODUTOS (ID);

CREATE INDEX IDX_PRODUTOS_GERAL ON PRODUTOS (ID, CATEGORIA_ID, FORNECEDOR_ID);

CREATE INDEX IDX_PESSOATIPOPARCEIRO_ID ON PESSOA_TIPO_PARCEIRO (PESSOA_ID);